PokeMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PokeMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PokeMVC/Controllers/MoveController.cs
using PokeMVC.Data;
using PokeMVC.Models;
using PokeMVC.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PokeMVC.Controllers
{
    [Authorize]
    public class MoveController : Controller
    {
        // GET: Move
        public ActionResult Index()
        {
            var moveService = new MoveService();
            var allMoves = moveService.GetMoves();

            return View(allMoves);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MoveCreate move)
        {
            if (!ModelState.IsValid) return View(move);

            var moveService = new MoveService();

            if (moveService.CreateMove(move))
            {
                TempData["SaveResult"]= "The move was added!";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "The move could not be added.");

            return View(move);
        }

        public ActionResult Details(int id)
        {
            var moveService = new MoveService();
            var move = moveService.GetMoveById(id);

            return View(move);
        }

        public ActionResult Edit(int id)
        {
            var moveService = new MoveService();
            var move = moveService.GetMoveById(id);
            var editedMove =
                new MoveEdit
                {
                    MoveId = move.MoveId,
                    MoveName = move.MoveName,
                    MovePower = move.MovePower,
                    MoveAccuracy = move.MoveAccuracy,
                    MovePP = move.MovePP,
                    ExtraEffect = move.ExtraEffect
                };

            return View(editedMove);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MoveEdit move)
        {
            if (!ModelState.IsValid) return View(move);

            if (move.MoveId != id)
            {
                ModelState.AddModelError("", "Id does not match");
                return View(move);
            }

            var moveService = new MoveService();
            
            if (moveService.UpdateMove(move))
            {
                TempData["SaveResult"] = "The move was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "The move could not be updated.");
            return View(move);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var moveService = new MoveService();
            var move = moveService.GetMoveById(id);

            return View(move);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var moveService = new MoveService();

            moveService.DeleteMove(id);

            TempData["SaveResult"] = "The move was deleted.";

            return RedirectToAction("Index");
        }
    }
}

PokeMVC/Controllers/TrainerController.cs
using PokeMVC.Data;
using PokeMVC.Models;
using PokeMVC.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace PokeMVC.Controllers
{
    [Authorize]
    public class TrainerController : Controller
    {
        // GET: Trainer
        public ActionResult Index()
        {
            var trainerService = new TrainerService();
            var allTrainers = trainerService.GetTrainers();

            return View(allTrainers);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TrainerCreate trainer)
        {
            if (!ModelState.IsValid) return View(trainer);

            var trainerService = new TrainerService();

            if (trainerService.CreateTrainer(trainer))
            {
                TempData["SaveResult"] = "The trainer was added!";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "The trainer could not be added.");

            return View(trainer);
        }

        public ActionResult Details(int id)
        {
            var trainerService = new TrainerService();
            var trainer = trainerService.GetTrainerById(id);

            return View(trainer);
        }

        public ActionResult Edit(int id)
        {
            var trainerService = new TrainerService();
            var trainer = trainerService.GetTrainerById(id);
            var editedTrainer =
                new TrainerEdit
                {
                    TrainerId = trainer.TrainerId,
                    Name = trainer.Name,
                    IsGymLeader = trainer.IsGymLeader,
                    IsEliteFour = trainer.IsEliteFour,
                    IsChampion = trainer.IsChampion
                };

            return View(editedTrainer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, TrainerEdit trainer)
        {
            if (!ModelState.IsValid) return View(trainer);

            if (trainer.TrainerId != id)
            {
                ModelState.AddModelError("", "Id does not match");
                return View(trainer);
            }

            var trainerService = new TrainerService();

            if (trainerService.UpdateTrainer(trainer))
            {
                TempData["SaveResult"] = "The trainer was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "The trainer could not be updated.");
            return View(trainer);
        }

        public ActionResult Delete(int id)
        {
            var trainerService = new TrainerService();

            var trainer = trainerService.GetTrainerById(id);

            return View(trainer);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var trainerService = new TrainerService();

            trainerService.DeleteTrainer(id);

            TempData["SaveResult"] = "The trainer was deleted.";

            return RedirectToAction("Index");
        }

        public ActionResult AddPokemonToTrainerTeam(int id)
        {
            var pokemonService = new PokemonService();

            var trainerService = new TrainerService();

            var trainer = trainerService.GetTrainerById(id);

            ViewBag.PokemonId = new SelectList(pokemonService.GetAllPokemon(), "PokemonId", "Species");

            return View(trainer);
        }

        [HttpPost]
        [ActionName("AddPokemonToTrainerTeam")]
        [ValidateAntiForgeryToken]
        public ActionResult AddPokemonToTrainerTeamPost(int pokemonId, int trainerId, TrainerDetail trainer)
        {
            var trainerService = new TrainerService();

            trainerService.AddPokemonToTrainerTeam(trainer.PokemonId, trainerId);

            TempData["SaveResult"] = "The Pokemon was added to the trainer's team.";

            return RedirectToAction("Index");
        }
    }
}

PokeMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PokeMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PokeMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "PokeMVC Home";
}

<div class="jumbotron">
    <h1><img src="https://fontmeme.com/permalink/200727/5e7386a09b3003f226e6eeba3d41d8bc.png" alt="pokemon-font" border="0"" alt="pokemon-font" border="0" /></h1>
    <p class="lead">
        PokeMVC is a database for all things Pokemon! You can use it to find information on Pokemon, Moves, and Trainers.
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Pokemon</h2>
        <p>
            The Pokemon table has information on Pokemon. You can visit it to find information on which regions Pokemon are from,
            which Pokemon are legendary or mythical, or evolution conditions.
        </p>
        @Html.ActionLink("Pokemon", "Index", "Pokemon", null, new { @class = "btn btn-primary btn-lg"})
    </div>
    <div class="col-md-4">
        <h2>Moves</h2>
        <p>
            Check the moves table for all information on moves. You can find the stats for a specific moves, as well as what extra
            effects a move can have!</p>
        <p>
        @Html.ActionLink("Moves", "Index", "Move", null, new { @class = "btn btn-primary btn-lg" })
</div>
    <div class="col-md-4">
        <h2>Trainers</h2>
        <p>
            The trainer table is where you want to go to prepare for battle! Use it to check the team of any tough trainer standing
            in your path to become Champion!</p>
        <p>
        @Html.ActionLink("Trainers", "Index", "Trainer", null, new { @class = "btn btn-primary btn-lg" })
</div>
</div>